### ISSUE TITLE
Can be bar cause slow down?

### ISSUE THREAD

**Issue by bubnenkoff** [kotet/progress#47]
I am doing processing of 400k values. Without progress bar I am getting result in 5 seconds. With it it's growing to max value, but it's growing much more slowly than without it?

Could it be reason of slow-down? How can I fix it?

**Comment by kotet** [comment]
Current implementation always draw regardless of the time when the previous drawing occurred.
Therefore, in the code below, the rendering process is performed `10 ^^ 6` times.
In some cases, this process slows down the total processing time.

```d
import progress;

void main()
{
	const N = 10 ^^ 6;
	auto b = new Bar();
	b.max = N;
	foreach (i; 0 .. N)
	{
		// Do something

		b.next();
	}
	b.finish();
}
```

I will fix it.
As a temporary solution, You can reduce the drawing process manually.

```d
import progress;

void main()
{
	const N = 10 ^^ 6;
	const skip = 1;
	auto b = new Bar();
	b.max = N / skip;
	foreach (i; 0 .. N)
	{
		// Do something

		if (i % skip == 0)
			b.next();
	}
	b.finish();
}
```
