### ISSUE TITLE
end value to do equal of max value

### ISSUE THREAD

**Issue by bubnenkoff** [kotet/progress#50]
See screenshot.
It's very strange that values are not same. Do you have any ideas why it can be wrong?

![123](https://cloud.githubusercontent.com/assets/6514326/25173880/62b41ba8-24fe-11e7-89b5-e0df40560d82.png)

**Comment by kotet** [comment]
Did you `finish()` when the task is completed?

**Comment by bubnenkoff** [comment]
Oh! I forgot!

**Comment by bubnenkoff** [comment]
One moment checked. 
![123](https://cloud.githubusercontent.com/assets/6514326/25177116/6489a4ba-2509-11e7-8092-dcdb3f95925c.png)

**Comment by kotet** [comment]
It may be a problem of float accuracy.
Validating the equality of a float using `==`, often causes problems.

**Comment by kotet** [comment]
For percentage display, use `b.suffix = {return b.percent.to!string ~ "/100";};`.

**Comment by bubnenkoff** [comment]
"Validating the equality of a float using ==, often causes problems."
And what usually use instead == ?

**Comment by kotet** [comment]
Make it an integer problem.
In this case, you can simply call next() every time.
