### ISSUE TITLE
Progress bar still not appears...

### ISSUE THREAD

**Issue by bubnenkoff** [kotet/progress#53]
![123](https://cloud.githubusercontent.com/assets/6514326/25422181/a0e90e14-2a68-11e7-86ed-589c7a053ce0.png)

![123](https://cloud.githubusercontent.com/assets/6514326/25422305/23515c58-2a69-11e7-9c07-dccaa32ff139.png)

Here is my code http://vpaste.net/5k7PP

I will try to provide the better example...

**Comment by kotet** [comment]
You should not use stdio / stderr while the progressbar is running.
For such rich application, please use libraries such as ncurses.
